// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Note struct {
	ID        string    `json:"id"`
	Mode      string    `json:"mode"`
	Content   []byte    `json:"content"`
	Salt      []byte    `json:"salt"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Title     string    `json:"title"`
}
