// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// Table for storing notes with public/private mode
type Note struct {
	ID string `json:"id"`
	// Pemilik note. List/Update/Delete hanya boleh oleh pemilik; Get/Unlock via share link tetap terbuka untuk siapapun.
	UserID string `json:"user_id"`
	// public: plaintext, private: nonce||ciphertext AES-GCM
	Mode string `json:"mode"`
	// plaintext for public, nonce||ciphertext for private
	Content []byte `json:"content"`
	// 16 byte random salt for private mode, empty for public
	Salt      []byte    `json:"salt"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Session struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	UserAgent string             `json:"user_agent"`
	CreatedAt time.Time          `json:"created_at"`
	ExpiresAt time.Time          `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type User struct {
	ID                    string             `json:"id"`
	Email                 string             `json:"email"`
	PasswordHash          string             `json:"password_hash"`
	EmailVerified         bool               `json:"email_verified"`
	VerificationTokenHash pgtype.Text        `json:"verification_token_hash"`
	VerificationExpiresAt pgtype.Timestamptz `json:"verification_expires_at"`
	// Sub ID dari Google OAuth, NULL kalau user belum pernah login via Google
	GoogleID pgtype.Text `json:"google_id"`
	// Bcrypt hash password yang MENUNGGU verifikasi email sebelum di-merge ke akun Google yang sudah ada
	PendingPasswordHash pgtype.Text `json:"pending_password_hash"`
	// SHA-256 dari token merge yang dikirim ke email
	PendingPasswordTokenHash pgtype.Text        `json:"pending_password_token_hash"`
	PendingPasswordExpiresAt pgtype.Timestamptz `json:"pending_password_expires_at"`
	CreatedAt                time.Time          `json:"created_at"`
}
