// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package sqlc

import (
	"context"
	"time"
)

const countNotesByUser = `-- name: CountNotesByUser :one
SELECT COUNT(*) FROM notes WHERE user_id = $1
`

func (q *Queries) CountNotesByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countNotesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNote = `-- name: CreateNote :one
INSERT INTO notes (id, user_id, mode, content, salt, title)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, mode, content, salt, title, created_at, updated_at
`

type CreateNoteParams struct {
	ID      string `json:"id"`
	UserID  string `json:"user_id"`
	Mode    string `json:"mode"`
	Content []byte `json:"content"`
	Salt    []byte `json:"salt"`
	Title   string `json:"title"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.ID,
		arg.UserID,
		arg.Mode,
		arg.Content,
		arg.Salt,
		arg.Title,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Mode,
		&i.Content,
		&i.Salt,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :execrows
DELETE FROM notes WHERE id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNote, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNote = `-- name: GetNote :one
SELECT id, user_id, mode, content, salt, title, created_at, updated_at FROM notes WHERE id = $1
`

func (q *Queries) GetNote(ctx context.Context, id string) (Note, error) {
	row := q.db.QueryRow(ctx, getNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Mode,
		&i.Content,
		&i.Salt,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotesByUser = `-- name: ListNotesByUser :many
SELECT id, mode, title, created_at, updated_at FROM notes WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListNotesByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListNotesByUserRow struct {
	ID        string    `json:"id"`
	Mode      string    `json:"mode"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListNotesByUser(ctx context.Context, arg ListNotesByUserParams) ([]ListNotesByUserRow, error) {
	rows, err := q.db.Query(ctx, listNotesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotesByUserRow
	for rows.Next() {
		var i ListNotesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNoteContent = `-- name: UpdateNoteContent :one
UPDATE notes
SET content = $2, title = $3, updated_at = now()
WHERE id = $1
RETURNING id, user_id, mode, content, salt, title, created_at, updated_at
`

type UpdateNoteContentParams struct {
	ID      string `json:"id"`
	Content []byte `json:"content"`
	Title   string `json:"title"`
}

func (q *Queries) UpdateNoteContent(ctx context.Context, arg UpdateNoteContentParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNoteContent, arg.ID, arg.Content, arg.Title)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Mode,
		&i.Content,
		&i.Salt,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
